title: MNH48 Translation - Terjemahan MNH48
description: "&#x202e;ترجمهن &#x202c;MNH48&#x202e; -  &#x202c;"
owner_name: MNH48
twitter_username: yayamnh48
github_username: mnh48
youtube_link: https://www.youtube.com/channel/UCnbL8SM08ViV43pZP5UuEhw/
timezone: Asia/Kuala_Lumpur
repository: mnh48/tl.mnh48.moe
remote_theme: mnh48/mnh48moe-theme

homepage:
  name: MNH48.moe
  wwwurl: www.mnh48.moe
  url: mnh48.moe

blog:
  name: MNH48.com
  wwwurl: www.mnh48.com
  url: mnh48.com

mnh48:
  picture: https://gravatar.com/avatar/75137565e1f032813be0b53122547ba7?s=200
  twitter: yayamnh48

plugins:
  - jekyll-redirect-from
  - jemoji
  - jekyll-mentions
  - jekyll-remote-theme

markdown: kramdown
kramdown:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - tables
    - strikethrough
    - superscript
    - with_to_data

